# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  #Configure vagrant Hostmanager
  config.hostmanager.enabled = false
  config.hostmanager.manage_hosts = true

  #Configure SSH
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["/root/.ssh/id_rsa.pub","~/.vagrant.d/insecure_private_key"]

  #Default Hostname
  #hostname_base = "{{ hostname_default }}"

  #configure web in a loop
  if {{ web_config }}
    (1..{{ web_aantal }}).each do |i|
      config.vm.define "klantnaam-web#{i}" do |web_config|
        web_config.vm.box = "ubuntu/focal64"
        web_config.vm.hostname = "klantnaam-web#{i}"
        web_config.vm.network :private_network, ip: "192.168.ipaddress.2#{i}"
        web_config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
        web_config.vm.provision :hostmanager
        web_config.vm.provider "virtualbox" do |vb|
          vb.memory = "{{ web_memory }}"
          vb.gui = false
          vb.name = "klantnaam-web#{i}"
        end
      end
    end
  end
  #configure lb in a loop
  if {{ lb_config }}
    (1..{{ lb_aantal }}).each do |i|
      config.vm.define "klantnaam-lb#{i}" do |lb_config|
        lb_config.vm.box = "ubuntu/focal64"
        lb_config.vm.hostname = "klantnaam-lb#{i}"
        lb_config.vm.network :private_network, ip: "192.168.ipaddress.3#{i}"
        lb_config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
        lb_config.vm.provision :hostmanager
        lb_config.vm.provider "virtualbox" do |vb|
          vb.memory = "{{ lb_memory }}"
          vb.gui = false
          vb.name = "klantnaam-lb#{i}"
        end
      end
    end
  end
  #configure db in a loop
  if {{ db_config }}
    (1..{{ db_aantal }}).each do |i|
      config.vm.define "klantnaam-db#{i}" do |db_config|
        db_config.vm.box = "ubuntu/focal64"
        db_config.vm.hostname = "klantnaam-db#{i}"
        db_config.vm.network :private_network, ip: "192.168.ipaddress.4#{i}"
        db_config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
        db_config.vm.provision :hostmanager
        db_config.vm.provider "virtualbox" do |vb|
          vb.memory = "{{ db_memory }}"
          vb.gui = false
          vb.name = "klantnaam-db#{i}"
        end
      end
    end
  end
end


