---
- name: Update apt update_cache
  apt:
    update_cache: yes

- name: Installeer apache
  apt:
    name: apache2
    state: present

- name: Maak index.php
  template:
    src: "/home/VM2/playbooks/roles/web/files/index.php"
    dest: "/var/www/html/index.php"

- name: Verwijder index.html
  file:
    path: /var/www/html/index.html
    state: absent
