---
- name: installeer haproxy
  package:
    name:
      - haproxy
    state: present
    update_cache: yes

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify:
  - restart haproxy