---
- name: Update apt update_cache
  apt:
    update_cache: yes

- name: install haproxy and socat
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - haproxy
    - socat
    gather_facts: yes

- name: enable haproxy
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED"
    line: "ENABLED=1"

- name: deploy haproxy config
  template:
    src: ./templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    backup: yes

- name: restart haproxy
  service: name=haproxy state=started
  
- name: restart haproxy
  service: name=haproxy state=restarted