# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  #Configure vagrant Hostmanager
  config.hostmanager.enabled = false
  config.hostmanager.manage_hosts = true

  #Configure SSH
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["/root/.ssh/id_rsa.pub","~/.vagrant.d/insecure_private_key"]

  #Default Hostname
  #hostname_base = "{{ hostname_default }}"

  #configure web in a loop
  if true
    (1..1).each do |i|
      config.vm.define "gert-48-test-web#{i}" do |web_config|
        web_config.vm.box = "ubuntu/focal64"
        web_config.vm.hostname = "gert-48-test-web#{i}"
        web_config.vm.network :private_network, ip: "192.168.48.2#{i}"
        web_config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
        web_config.vm.provision :hostmanager
        web_config.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.gui = false
          vb.name = "gert-48-test-web#{i}"
        end
      end
    end
  end
  #configure lb in a loop
  if false
    (1..0).each do |i|
      config.vm.define "gert-48-test-lb#{i}" do |lb_config|
        lb_config.vm.box = "ubuntu/focal64"
        lb_config.vm.hostname = "gert-48-test-lb#{i}"
        lb_config.vm.network :private_network, ip: "192.168.48.3#{i}"
        lb_config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
        lb_config.vm.provision :hostmanager
        lb_config.vm.provider "virtualbox" do |vb|
          vb.memory = "0"
          vb.gui = false
          vb.name = "gert-48-test-lb#{i}"
        end
      end
    end
  end
  #configure db in a loop
  if true
    (1..1).each do |i|
      config.vm.define "gert-48-test-db#{i}" do |db_config|
        db_config.vm.box = "ubuntu/focal64"
        db_config.vm.hostname = "gert-48-test-db#{i}"
        db_config.vm.network :private_network, ip: "192.168.48.4#{i}"
        db_config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
        db_config.vm.provision :hostmanager
        db_config.vm.provider "virtualbox" do |vb|
          vb.memory = "2048"
          vb.gui = false
          vb.name = "gert-48-test-db#{i}"
        end
      end
    end
  end
end


